import type { CardInventory } from './types'

/**
 * 测试用的背包数据（模拟战役外的背包系统）
 * 这些是原始卡牌数据，不会被战斗直接修改
 */
export const testInventory: CardInventory[] = [
  {
    id: 'card-imperium-infantry-1',
    type: 'unit',
    unitTemplateId: 'imperium-infantry',
    maxHp: 20, // 原始最大生命值
    currentHp: 20, // 当前生命值
    status: 'available', // MVP版本：初始状态为可用
  },
  {
    id: 'card-imperium-infantry-2',
    type: 'unit',
    unitTemplateId: 'imperium-infantry',
    maxHp: 20,
    currentHp: 20,
    status: 'available',
  },
  {
    id: 'card-imperium-infantry-3',
    type: 'unit',
    unitTemplateId: 'imperium-infantry',
    maxHp: 20,
    currentHp: 20,
    status: 'available',
  },
  {
    id: 'card-imperium-infantry-4',
    type: 'unit',
    unitTemplateId: 'imperium-infantry',
    maxHp: 20,
    currentHp: 20,
    status: 'available',
  },
  {
    id: 'card-imperium-infantry-5',
    type: 'unit',
    unitTemplateId: 'imperium-infantry',
    maxHp: 20,
    currentHp: 20,
    status: 'available',
  },
  {
    id: 'card-imperium-infantry-6',
    type: 'unit',
    unitTemplateId: 'imperium-infantry',
    maxHp: 20,
    currentHp: 20,
    status: 'available',
  },
  {
    id: 'card-imperium-infantry-7',
    type: 'unit',
    unitTemplateId: 'imperium-infantry',
    maxHp: 20,
    currentHp: 20,
    status: 'available',
  },
  {
    id: 'card-imperium-infantry-8',
    type: 'unit',
    unitTemplateId: 'imperium-infantry',
    maxHp: 20,
    currentHp: 20,
    status: 'available',
  },
  {
    id: 'card-imperium-artillery-1',
    type: 'unit',
    unitTemplateId: 'imperium-artillery',
    maxHp: 16,
    currentHp: 16,
    status: 'available',
  },
  {
    id: 'card-imperium-artillery-2',
    type: 'unit',
    unitTemplateId: 'imperium-artillery',
    maxHp: 16,
    currentHp: 16,
    status: 'available',
  },
  {
    id: 'card-ork-boy-1',
    type: 'unit',
    unitTemplateId: 'ork-boy',
    maxHp: 18,
    currentHp: 18,
    status: 'available',
  },
  {
    id: 'card-ork-boy-2',
    type: 'unit',
    unitTemplateId: 'ork-boy',
    maxHp: 18,
    currentHp: 18,
    status: 'available',
  },
  {
    id: 'card-ork-boy-3',
    type: 'unit',
    unitTemplateId: 'ork-boy',
    maxHp: 18,
    currentHp: 18,
    status: 'available',
  },
  {
    id: 'card-ork-boy-4',
    type: 'unit',
    unitTemplateId: 'ork-boy',
    maxHp: 18,
    currentHp: 18,
    status: 'available',
  },
  {
    id: 'card-ork-boy-5',
    type: 'unit',
    unitTemplateId: 'ork-boy',
    maxHp: 18,
    currentHp: 18,
    status: 'available',
  },
  {
    id: 'card-ork-boy-6',
    type: 'unit',
    unitTemplateId: 'ork-boy',
    maxHp: 18,
    currentHp: 18,
    status: 'available',
  },
  {
    id: 'card-ork-boy-7',
    type: 'unit',
    unitTemplateId: 'ork-boy',
    maxHp: 18,
    currentHp: 18,
    status: 'available',
  },
  {
    id: 'card-ork-boy-8',
    type: 'unit',
    unitTemplateId: 'ork-boy',
    maxHp: 18,
    currentHp: 18,
    status: 'available',
  },
  // 兽人纸飞机（敌方空中单位）
  {
    id: 'card-ork-paper-plane-1',
    type: 'unit',
    unitTemplateId: 'ork-paper-plane',
    maxHp: 8,
    currentHp: 8,
    status: 'available',
  },
  {
    id: 'card-ork-paper-plane-2',
    type: 'unit',
    unitTemplateId: 'ork-paper-plane',
    maxHp: 8,
    currentHp: 8,
    status: 'available',
  },
  {
    id: 'card-ork-paper-plane-3',
    type: 'unit',
    unitTemplateId: 'ork-paper-plane',
    maxHp: 8,
    currentHp: 8,
    status: 'available',
  },
  // 帝国空中斥候（我方空中单位）
  {
    id: 'card-imperium-air-scout-1',
    type: 'unit',
    unitTemplateId: 'imperium-air-scout',
    maxHp: 16,
    currentHp: 16,
    status: 'available',
    displayName: '帝国空中斥候#1',
  },
  {
    id: 'card-imperium-air-scout-2',
    type: 'unit',
    unitTemplateId: 'imperium-air-scout',
    maxHp: 16,
    currentHp: 16,
    status: 'available',
    displayName: '帝国空中斥候#2',
  },
  {
    id: 'card-imperium-air-scout-3',
    type: 'unit',
    unitTemplateId: 'imperium-air-scout',
    maxHp: 16,
    currentHp: 16,
    status: 'available',
    displayName: '帝国空中斥候#3',
  },
  {
    id: 'card-imperium-air-scout-4',
    type: 'unit',
    unitTemplateId: 'imperium-air-scout',
    maxHp: 16,
    currentHp: 16,
    status: 'available',
    displayName: '帝国空中斥候#4',
  },
  // 勇气光环（法术卡牌）
  {
    id: 'card-courage-aura-1',
    type: 'spell',
    unitTemplateId: 'courage-aura',
    maxHp: 0, // 法术卡牌没有生命值
    currentHp: 0,
    status: 'available',
  },
  // 可以添加更多测试卡牌...
]

